language: elixir
elixir:
  - 1.10.4
  - 1.11.4
  - 1.12.3
  - 1.13.4
otp_release:
  - 22.1
  - 23.3.1
  - 24.3.1
matrix:
  exclude:
    - elixir: 1.11.4
      otp_release: 24.3.1
    - elixir: 1.10.4
      otp_release: 23.3.1
    - elixir: 1.10.4
      otp_release: 24.3.1
services:
  - rabbitmq
addons:
  apt:
    packages:
      - rabbitmq-server
